### ISSUE TITLE
关于建议及一直抖音解析重试中的问题

### ISSUE THREAD

**Issue by nuoxianCN** [shinianj/zhenxun_plugin_DouyinShare#12]
环境：Win Server 2012 R2
Python版本：3.9
建议：初次使用时可能需要安装包：requests、tqdm（因为我使用时插件报错。重启了2次后才手动安装了这2个包。希望在描述中提一下）
问题：发送抖音链接后cmd一直显示 【抖音解析尝试重连......】
问题日志：暂无
问题图片：
![MFC2MOY4 RLGN)SINXZJJ(H](https://user-images.githubusercontent.com/56551535/211565503-8ce85eb6-57bc-4f82-b4a4-3ae694faa899.png)

**Comment by Yql66** [comment]
我也是这样

**Comment by nuoxianCN** [comment]
> 我也是这样

api接口是正常的

**Comment by shinianj** [comment]
下午我修一下吧，前几天在忙其他的

**Comment by shinianj** [comment]
> > 我也是这样
> 
> api接口是正常的

![)%_Y ``{UVBBO@ELYG~%M39](https://user-images.githubusercontent.com/105840558/211715645-0b44a006-6166-434d-86af-cdf62e23b2f5.png)
请问能否解释下，这样的解析，能说是正常吗，我连续试了6个链接，甚至是文档里的示例链接。如果都是这个返回，我觉得我得另谋出路了

**Comment by nuoxianCN** [comment]
> > > 我也是这样
> > 
> > 
> > api接口是正常的
> 
> ![)%_Y ``{UVBBO@ELYG~%M39](https://user-images.githubusercontent.com/105840558/211715645-0b44a006-6166-434d-86af-cdf62e23b2f5.png) 请问能否解释下，这样的解析，能说是正常吗，我连续试了6个链接，甚至是文档里的示例链接。如果都是这个返回，我觉得我得另谋出路了

昨天的时候是正常的，现在又出问题了。需要等待修复
![Uploading Screenshot_2023-01-10-21-57-09-355_com.tencent.mm.jpg…]()

**Comment by nuoxianCN** [comment]
> > > 我也是这样
> > 
> > 
> > api接口是正常的
> 
> ![)%_Y ``{UVBBO@ELYG~%M39](https://user-images.githubusercontent.com/105840558/211715645-0b44a006-6166-434d-86af-cdf62e23b2f5.png) 请问能否解释下，这样的解析，能说是正常吗，我连续试了6个链接，甚至是文档里的示例链接。如果都是这个返回，我觉得我得另谋出路了

目前已临时修复，原因为API服务器可能被抖音屏蔽，导致无法获取相关内容而导致的问题。目前已临时用其他服务器搭建桥接。感谢你对于API的支持~！

**Comment by nuoxianCN** [comment]
另外，目前还是有重连尝试中的问题

**Comment by shinianj** [comment]
> 另外，目前还是有重连尝试中的问题。且我机器人使用此插件后，将无法触发机器人对话功能(?)

机器人对话功能需要调整优先级，真寻的ai优先级应该是999，抖音插件的优先级为15，需要把抖音插件的优先级改为999

**Comment by shinianj** [comment]
现在已经全部修复，插件优先级也不用修改了，不过分享卡片已经失效（被抖音噶了）

**Comment by shinianj** [comment]
若已经没有问题，请关闭issue
