### ISSUE TITLE
发送抖音链接，机器人没反应

### ISSUE THREAD

**Issue by SecretLoved** [shinianj/zhenxun_plugin_DouyinShare#4]
![image](https://user-images.githubusercontent.com/73172198/191885260-3faf3fc5-7658-44d5-8daa-f9ee03e0fee8.png)
发送抖音链接后，机器人没反应

**Comment by shinianj** [comment]
触发的词条为“复制打开抖音”，所以你需要稍稍改改分享的消息（我过段时间更新的时候会用新的匹配方法的）

**Comment by SecretLoved** [comment]
> 触发的词条为“复制打开抖音”，所以你需要稍稍改改分享的消息（我过段时间更新的时候会用新的匹配方法的）

了解了
