### ISSUE TITLE
报错无法使用(?)

### ISSUE THREAD

**Issue by xANoyU** [shinianj/zhenxun_plugin_DouyinShare#6]
[新文件 1.txt](https://github.com/shinianj/zhenxun_plugin_DouyinShare/files/9920368/1.txt)

**Comment by xANoyU** [comment]
> 请提供使用指令时发送的链接

5.35 kpd:/ 复制打开抖音，看看【Vonr的图文作品】情头真好看 我们复合吧 # 情头 https://v.douyin.com/M7k4Ftj/

我又试了一遍, 视频内容的链接就可以正常发送
如果里面是图片的话就会报错

**Comment by xANoyU** [comment]
> 请提供使用指令时发送的链接

5.35 kpd:/ 复制打开抖音，看看【Vonr的图文作品】情头真好看 我们复合吧 # 情头 https://v.douyin.com/M7k4Ftj/

我又试了一遍, 视频内容的链接就可以正常发送
如果里面是图片的话就会报错

**Comment by xANoyU** [comment]
> 请提供使用指令时发送的链接

5.35 kpd:/ 复制打开抖音，看看【Vonr的图文作品】情头真好看 我们复合吧 # 情头 https://v.douyin.com/M7k4Ftj/

我又试了一遍, 视频内容的链接就可以正常发送
如果里面是图片的话就会报错

**Comment by xANoyU** [comment]
> 请提供使用指令时发送的链接

5.35 kpd:/ 复制打开抖音，看看【Vonr的图文作品】情头真好看 我们复合吧 # 情头 https://v.douyin.com/M7k4Ftj/

我又试了一遍, 视频内容的链接就可以正常发送
如果里面是图片的话就会报错

**Comment by shinianj** [comment]
图文目前没法支持（以前发现了，但是我觉得应该没人会遇上所以就没说）
