### ISSUE TITLE
抖音视频分享报错

### ISSUE THREAD

**Issue by Yql66** [shinianj/zhenxun_plugin_DouyinShare#8]
![T{I)G%}()TI_XBEGPF`NSC](https://user-images.githubusercontent.com/111969738/209395437-12533beb-354b-4f38-b8be-ee573843b955.png)

**Comment by shinianj** [comment]
已修复（其实这个可以无视，毕竟本身api的问题）

**Comment by Yql66** [comment]
好的，十分感谢
