### ISSUE TITLE
分享链接无法识别

### ISSUE THREAD

**Issue by TQL1** [shinianj/zhenxun_plugin_DouyinShare#9]

**Comment by TQL1** [comment]
![Uploading Screenshot_20221226_212908_com.microsoft.rdc.android.jpg…]()

**Comment by TQL1** [comment]
https://s2.loli.net/2022/12/26/H4lnXPETMYfcOwa.jpg

**Comment by shinianj** [comment]
分享链接被你的另外插件给拦截了，把插件的优先级调高或者和他们一样（一样要注意顺序）
